<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net8.0-windows</TargetFramework><UseWPF>true</UseWPF><ImplicitUsings>enable</ImplicitUsings></PropertyGroup>
  <ItemGroup><Compile Remove="Baseline/**/*.cs" /><ProjectReference Include="Baseline/Baseline.csproj" /><ProjectReference Include="../../LaunchPad.csproj" /><FrameworkReference Include="Microsoft.WindowsDesktop.App.WindowsForms" /></ItemGroup>
</Project>
