<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><TargetFramework>net8.0-windows</TargetFramework><OutputType>Exe</OutputType><UseWPF>true</UseWPF><ImplicitUsings>enable</ImplicitUsings></PropertyGroup><ItemGroup><Compile Remove="Fixture/**/*.cs" /><ProjectReference Include="../../LaunchPad.csproj" /></ItemGroup></Project>
